### ISSUE TITLE
Question FPS

### ISSUE THREAD

**Issue by wenjun90** [zzzxxxttt/simple_detectron2_EfficientDet#2]
Hello,

Could I ask you the FPS you obtain with detectron_efficientNet on COCO dataset?
How I can set the backbone EfficientNet b1,...,b3

Thank you

**Comment by zzzxxxttt** [comment]
Hi @wenjun90 

The inference time of EfficientDet-D0 is ~54ms/img on a Tesla V100 GPU, I think there is still room for optimization.

If you want to train D1, according to the [official config](https://github.com/google/automl/blob/master/efficientdet/hparams_config.py):
```
            name='efficientdet-d1',
            backbone_name='efficientnet-b1',
            image_size=640,
            fpn_num_filters=88,
            fpn_cell_repeats=4,
            box_class_repeats=3,
```

just modify the configs/EfficientDet_D0.yaml:

```
MODEL:
    WEIGHTS: "/home/b1_detectron2.pth"
    EfficientNet:
        VERSION: 1
    FPN:
        OUT_CHANNELS: 88
        REPEAT: 4
    RETINANET:
        NUM_CONVS: 3
```
and of course, you need to adjust the input size accordingly.
